// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/welcome": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/welcome" | "/login" | "/register";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/" | "/welcome";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/welcome.tsx": {
    id: "routes/welcome";
    page: "/welcome";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/login" | "/register";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/welcome": typeof import("./app/routes/welcome.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
};